/* Generated by JTB 1.4.7 */
package type.visitor;

import type.syntaxtree.*;
import java.util.*;

public class DepthFirstRetVisitor<R> implements IRetVisitor<R> {


  public R visit(final NodeChoice n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    final R nRes = n.choice.accept(this);
    return nRes;
  }

  public R visit(final NodeList n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    R nRes = null;
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      @SuppressWarnings("unused")
      final R sRes = e.next().accept(this);
    }
    return nRes;
  }

  public R visit(final NodeListOptional n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    if (n.present()) {
      R nRes = null;
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        @SuppressWarnings("unused")
        R sRes = e.next().accept(this);
        }
      return nRes;
    } else
      return null;
  }

  public R visit(final NodeOptional n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    if (n.present()) {
      final R nRes = n.node.accept(this);
      return nRes;
    } else
      return null;
  }

  public R visit(final NodeSequence n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    R nRes = null;
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      @SuppressWarnings("unused")
      R subRet = e.next().accept(this);
    }
    return nRes;
  }

  public R visit(final NodeTCF n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    R nRes = null;
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return nRes;
  }

  public R visit(final NodeToken n) {
    /* You have to adapt which data is returned (result variables below are just examples) */
    R nRes = null;
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return nRes;
  }

  public R visit(final Goal n) {
    R nRes = null;
    // f0 -> MainClass()
    n.f0.accept(this);
    // f1 -> ( TypeDeclaration() )*
    n.f1.accept(this);
    // f2 -> <EOF>
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final MainClass n) {
    R nRes = null;
    // f0 -> "class"
    n.f0.accept(this);
    // f1 -> Identifier()
    n.f1.accept(this);
    // f2 -> "{"
    n.f2.accept(this);
    // f3 -> "public"
    n.f3.accept(this);
    // f4 -> "static"
    n.f4.accept(this);
    // f5 -> "void"
    n.f5.accept(this);
    // f6 -> "main"
    n.f6.accept(this);
    // f7 -> "("
    n.f7.accept(this);
    // f8 -> "String"
    n.f8.accept(this);
    // f9 -> "["
    n.f9.accept(this);
    // f10 -> "]"
    n.f10.accept(this);
    // f11 -> Identifier()
    n.f11.accept(this);
    // f12 -> ")"
    n.f12.accept(this);
    // f13 -> "{"
    n.f13.accept(this);
    // f14 -> ( VarDeclaration() )*
    n.f14.accept(this);
    // f15 -> ( Statement() )*
    n.f15.accept(this);
    // f16 -> "}"
    n.f16.accept(this);
    // f17 -> "}"
    n.f17.accept(this);
    return nRes;
  }

  public R visit(final TypeDeclaration n) {
    R nRes = null;
    // f0 -> . %0 ClassDeclaration()
    // .. .. | %1 ClassExtendsDeclaration()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ClassDeclaration n) {
    R nRes = null;
    // f0 -> "class"
    n.f0.accept(this);
    // f1 -> Identifier()
    n.f1.accept(this);
    // f2 -> "{"
    n.f2.accept(this);
    // f3 -> ( VarDeclaration() )*
    n.f3.accept(this);
    // f4 -> ( MethodDeclaration() )*
    n.f4.accept(this);
    // f5 -> "}"
    n.f5.accept(this);
    return nRes;
  }

  public R visit(final ClassExtendsDeclaration n) {
    R nRes = null;
    // f0 -> "class"
    n.f0.accept(this);
    // f1 -> Identifier()
    n.f1.accept(this);
    // f2 -> "extends"
    n.f2.accept(this);
    // f3 -> Identifier()
    n.f3.accept(this);
    // f4 -> "{"
    n.f4.accept(this);
    // f5 -> ( VarDeclaration() )*
    n.f5.accept(this);
    // f6 -> ( MethodDeclaration() )*
    n.f6.accept(this);
    // f7 -> "}"
    n.f7.accept(this);
    return nRes;
  }

  public R visit(final VarDeclaration n) {
    R nRes = null;
    // f0 -> Type()
    n.f0.accept(this);
    // f1 -> Identifier()
    n.f1.accept(this);
    // f2 -> ";"
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final MethodDeclaration n) {
    R nRes = null;
    // f0 -> "public"
    n.f0.accept(this);
    // f1 -> Type()
    n.f1.accept(this);
    // f2 -> Identifier()
    n.f2.accept(this);
    // f3 -> "("
    n.f3.accept(this);
    // f4 -> ( FormalParameterList() )?
    n.f4.accept(this);
    // f5 -> ")"
    n.f5.accept(this);
    // f6 -> "{"
    n.f6.accept(this);
    // f7 -> ( VarDeclaration() )*
    n.f7.accept(this);
    // f8 -> ( Statement() )*
    n.f8.accept(this);
    // f9 -> "return"
    n.f9.accept(this);
    // f10 -> Expression()
    n.f10.accept(this);
    // f11 -> ";"
    n.f11.accept(this);
    // f12 -> "}"
    n.f12.accept(this);
    return nRes;
  }

  public R visit(final FormalParameterList n) {
    R nRes = null;
    // f0 -> FormalParameter()
    n.f0.accept(this);
    // f1 -> ( FormalParameterRest() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final FormalParameter n) {
    R nRes = null;
    // f0 -> Type()
    n.f0.accept(this);
    // f1 -> Identifier()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final FormalParameterRest n) {
    R nRes = null;
    // f0 -> ","
    n.f0.accept(this);
    // f1 -> FormalParameter()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final Type n) {
    R nRes = null;
    // f0 -> . %0 ArrayType()
    // .. .. | %1 BooleanType()
    // .. .. | %2 IntegerType()
    // .. .. | %3 Identifier()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ArrayType n) {
    R nRes = null;
    // f0 -> "int"
    n.f0.accept(this);
    // f1 -> "["
    n.f1.accept(this);
    // f2 -> "]"
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final BooleanType n) {
    R nRes = null;
    // f0 -> "boolean"
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final IntegerType n) {
    R nRes = null;
    // f0 -> "int"
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Statement n) {
    R nRes = null;
    // f0 -> . %0 Block()
    // .. .. | %1 AssignmentStatement()
    // .. .. | %2 ArrayAssignmentStatement()
    // .. .. | %3 IfStatement()
    // .. .. | %4 WhileStatement()
    // .. .. | %5 PrintStatement()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Block n) {
    R nRes = null;
    // f0 -> "{"
    n.f0.accept(this);
    // f1 -> ( Statement() )*
    n.f1.accept(this);
    // f2 -> "}"
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final AssignmentStatement n) {
    R nRes = null;
    // f0 -> Identifier()
    n.f0.accept(this);
    // f1 -> "="
    n.f1.accept(this);
    // f2 -> Expression()
    n.f2.accept(this);
    // f3 -> ";"
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final ArrayAssignmentStatement n) {
    R nRes = null;
    // f0 -> Identifier()
    n.f0.accept(this);
    // f1 -> "["
    n.f1.accept(this);
    // f2 -> Expression()
    n.f2.accept(this);
    // f3 -> "]"
    n.f3.accept(this);
    // f4 -> "="
    n.f4.accept(this);
    // f5 -> Expression()
    n.f5.accept(this);
    // f6 -> ";"
    n.f6.accept(this);
    return nRes;
  }

  public R visit(final IfStatement n) {
    R nRes = null;
    // f0 -> "if"
    n.f0.accept(this);
    // f1 -> "("
    n.f1.accept(this);
    // f2 -> Expression()
    n.f2.accept(this);
    // f3 -> ")"
    n.f3.accept(this);
    // f4 -> Statement()
    n.f4.accept(this);
    // f5 -> "else"
    n.f5.accept(this);
    // f6 -> Statement()
    n.f6.accept(this);
    return nRes;
  }

  public R visit(final WhileStatement n) {
    R nRes = null;
    // f0 -> "while"
    n.f0.accept(this);
    // f1 -> "("
    n.f1.accept(this);
    // f2 -> Expression()
    n.f2.accept(this);
    // f3 -> ")"
    n.f3.accept(this);
    // f4 -> Statement()
    n.f4.accept(this);
    return nRes;
  }

  public R visit(final PrintStatement n) {
    R nRes = null;
    // f0 -> "System.out.println"
    n.f0.accept(this);
    // f1 -> "("
    n.f1.accept(this);
    // f2 -> Expression()
    n.f2.accept(this);
    // f3 -> ")"
    n.f3.accept(this);
    // f4 -> ";"
    n.f4.accept(this);
    return nRes;
  }

  public R visit(final Expression n) {
    R nRes = null;
    // f0 -> . %0 AndExpression()
    // .. .. | %1 CompareExpression()
    // .. .. | %2 PlusExpression()
    // .. .. | %3 MinusExpression()
    // .. .. | %4 TimesExpression()
    // .. .. | %5 ArrayLookup()
    // .. .. | %6 ArrayLength()
    // .. .. | %7 MessageSend()
    // .. .. | %8 PrimaryExpression()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final AndExpression n) {
    R nRes = null;
    // f0 -> PrimaryExpression()
    n.f0.accept(this);
    // f1 -> "&&"
    n.f1.accept(this);
    // f2 -> PrimaryExpression()
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final CompareExpression n) {
    R nRes = null;
    // f0 -> PrimaryExpression()
    n.f0.accept(this);
    // f1 -> "<"
    n.f1.accept(this);
    // f2 -> PrimaryExpression()
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final PlusExpression n) {
    R nRes = null;
    // f0 -> PrimaryExpression()
    n.f0.accept(this);
    // f1 -> "+"
    n.f1.accept(this);
    // f2 -> PrimaryExpression()
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final MinusExpression n) {
    R nRes = null;
    // f0 -> PrimaryExpression()
    n.f0.accept(this);
    // f1 -> "-"
    n.f1.accept(this);
    // f2 -> PrimaryExpression()
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final TimesExpression n) {
    R nRes = null;
    // f0 -> PrimaryExpression()
    n.f0.accept(this);
    // f1 -> "*"
    n.f1.accept(this);
    // f2 -> PrimaryExpression()
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final ArrayLookup n) {
    R nRes = null;
    // f0 -> PrimaryExpression()
    n.f0.accept(this);
    // f1 -> "["
    n.f1.accept(this);
    // f2 -> PrimaryExpression()
    n.f2.accept(this);
    // f3 -> "]"
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final ArrayLength n) {
    R nRes = null;
    // f0 -> PrimaryExpression()
    n.f0.accept(this);
    // f1 -> "."
    n.f1.accept(this);
    // f2 -> "length"
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final MessageSend n) {
    R nRes = null;
    // f0 -> PrimaryExpression()
    n.f0.accept(this);
    // f1 -> "."
    n.f1.accept(this);
    // f2 -> Identifier()
    n.f2.accept(this);
    // f3 -> "("
    n.f3.accept(this);
    // f4 -> ( ExpressionList() )?
    n.f4.accept(this);
    // f5 -> ")"
    n.f5.accept(this);
    return nRes;
  }

  public R visit(final ExpressionList n) {
    R nRes = null;
    // f0 -> Expression()
    n.f0.accept(this);
    // f1 -> ( ExpressionRest() )*
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ExpressionRest n) {
    R nRes = null;
    // f0 -> ","
    n.f0.accept(this);
    // f1 -> Expression()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final PrimaryExpression n) {
    R nRes = null;
    // f0 -> . %0 IntegerLiteral()
    // .. .. | %1 TrueLiteral()
    // .. .. | %2 FalseLiteral()
    // .. .. | %3 Identifier()
    // .. .. | %4 ThisExpression()
    // .. .. | %5 ArrayAllocationExpression()
    // .. .. | %6 AllocationExpression()
    // .. .. | %7 NotExpression()
    // .. .. | %8 BracketExpression()
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final IntegerLiteral n) {
    R nRes = null;
    // f0 -> <INTEGER_LITERAL>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final TrueLiteral n) {
    R nRes = null;
    // f0 -> "true"
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final FalseLiteral n) {
    R nRes = null;
    // f0 -> "false"
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Identifier n) {
    R nRes = null;
    // f0 -> <IDENTIFIER>
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ThisExpression n) {
    R nRes = null;
    // f0 -> "this"
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ArrayAllocationExpression n) {
    R nRes = null;
    // f0 -> "new"
    n.f0.accept(this);
    // f1 -> "int"
    n.f1.accept(this);
    // f2 -> "["
    n.f2.accept(this);
    // f3 -> Expression()
    n.f3.accept(this);
    // f4 -> "]"
    n.f4.accept(this);
    return nRes;
  }

  public R visit(final AllocationExpression n) {
    R nRes = null;
    // f0 -> "new"
    n.f0.accept(this);
    // f1 -> Identifier()
    n.f1.accept(this);
    // f2 -> "("
    n.f2.accept(this);
    // f3 -> ")"
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final NotExpression n) {
    R nRes = null;
    // f0 -> "!"
    n.f0.accept(this);
    // f1 -> Expression()
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final BracketExpression n) {
    R nRes = null;
    // f0 -> "("
    n.f0.accept(this);
    // f1 -> Expression()
    n.f1.accept(this);
    // f2 -> ")"
    n.f2.accept(this);
    return nRes;
  }

}
