/* Generated by JTB 1.4.7 */
package type.syntaxtree;

import type.visitor.*;

public class ArrayLookup implements INode {

  public PrimaryExpression f0;

  public NodeToken f1;

  public PrimaryExpression f2;

  public NodeToken f3;

  private static final long serialVersionUID = 147L;

  public ArrayLookup(final PrimaryExpression n0, final NodeToken n1, final PrimaryExpression n2, final NodeToken n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
