/* Generated by JTB 1.4.7 */
package type.syntaxtree;

import type.visitor.*;

public class ClassExtendsDeclaration implements INode {

  public NodeToken f0;

  public Identifier f1;

  public NodeToken f2;

  public Identifier f3;

  public NodeToken f4;

  public NodeListOptional f5;

  public NodeListOptional f6;

  public NodeToken f7;

  private static final long serialVersionUID = 147L;

  public ClassExtendsDeclaration(final NodeToken n0, final Identifier n1, final NodeToken n2, final Identifier n3, final NodeToken n4, final NodeListOptional n5, final NodeListOptional n6, final NodeToken n7) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
