/* Generated by JTB 1.4.7 */
package type.visitor;

import type.syntaxtree.*;

public interface IVoidArguVisitor<A> {

  public void visit(final NodeChoice n, final A argu);

  public void visit(final NodeList n, final A argu);

  public void visit(final NodeListOptional n, final A argu);

  public void visit(final NodeOptional n, final A argu);

  public void visit(final NodeSequence n, final A argu);

  public void visit(final NodeTCF n, final A argu);

  public void visit(final NodeToken n, final A argu);

  public void visit(final Goal n, final A argu);

  public void visit(final MainClass n, final A argu);

  public void visit(final TypeDeclaration n, final A argu);

  public void visit(final ClassDeclaration n, final A argu);

  public void visit(final ClassExtendsDeclaration n, final A argu);

  public void visit(final VarDeclaration n, final A argu);

  public void visit(final MethodDeclaration n, final A argu);

  public void visit(final FormalParameterList n, final A argu);

  public void visit(final FormalParameter n, final A argu);

  public void visit(final FormalParameterRest n, final A argu);

  public void visit(final Type n, final A argu);

  public void visit(final ArrayType n, final A argu);

  public void visit(final BooleanType n, final A argu);

  public void visit(final IntegerType n, final A argu);

  public void visit(final Statement n, final A argu);

  public void visit(final Block n, final A argu);

  public void visit(final AssignmentStatement n, final A argu);

  public void visit(final ArrayAssignmentStatement n, final A argu);

  public void visit(final IfStatement n, final A argu);

  public void visit(final WhileStatement n, final A argu);

  public void visit(final PrintStatement n, final A argu);

  public void visit(final Expression n, final A argu);

  public void visit(final AndExpression n, final A argu);

  public void visit(final CompareExpression n, final A argu);

  public void visit(final PlusExpression n, final A argu);

  public void visit(final MinusExpression n, final A argu);

  public void visit(final TimesExpression n, final A argu);

  public void visit(final ArrayLookup n, final A argu);

  public void visit(final ArrayLength n, final A argu);

  public void visit(final MessageSend n, final A argu);

  public void visit(final ExpressionList n, final A argu);

  public void visit(final ExpressionRest n, final A argu);

  public void visit(final PrimaryExpression n, final A argu);

  public void visit(final IntegerLiteral n, final A argu);

  public void visit(final TrueLiteral n, final A argu);

  public void visit(final FalseLiteral n, final A argu);

  public void visit(final Identifier n, final A argu);

  public void visit(final ThisExpression n, final A argu);

  public void visit(final ArrayAllocationExpression n, final A argu);

  public void visit(final AllocationExpression n, final A argu);

  public void visit(final NotExpression n, final A argu);

  public void visit(final BracketExpression n, final A argu);

}
